services:
  seed:
    build: backend
    command: yarn seed
    restart: "no"
    ports:
      - 9001:9001
    networks:
      - medusa-network
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://medusa-starter:medusa-password@postgres/medusa-starter

networks:
  medusa-network:
